# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\x1a\x1bgoogle/protobuf/empty.proto\".\n\nSensorData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x05\"3\n\x0fSensorDataBatch\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.sensor.SensorData2L\n\rSensorService\x12;\n\x08SendData\x12\x17.sensor.SensorDataBatch\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=53
  _globals['_SENSORDATA']._serialized_end=99
  _globals['_SENSORDATABATCH']._serialized_start=101
  _globals['_SENSORDATABATCH']._serialized_end=152
  _globals['_SENSORSERVICE']._serialized_start=154
  _globals['_SENSORSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
